name: Setup
description: Perform standard setup and install dependencies using pnpm.

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Install node
      uses: actions/setup-node@v6
      with:
        cache: pnpm
        node-version: 26.4.0
    - name: Install Vite+
      uses: voidzero-dev/setup-vp@v1.17.0
      with:
        node-manager: false
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
