name: Setup
description: Perform standard setup and install dependencies using pnpm.
inputs:
  node-version:
    description: The version of Node.js to install
    required: true
    default: 24.5.0
  working-directory:
    description: The directory within which dependencies should be installed with PNPM
    required: true
    default: .

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with: 
        package_json_file: ${{ inputs.working-directory }}/package.json

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install
