packages:
  - apps/*
  - packages/*

patchedDependencies:
  astro-tweet@0.0.6: patches/astro-tweet.patch

supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current

allowBuilds:
  "@mixedbread/cli": true
  esbuild: false
  msgpackr-extract: false
  msw: false
  sharp: false

catalogMode: prefer

catalog:
  "@astrojs/compiler-rs": ^0.3.2
  "@astrojs/mdx": ^7.0.5
  "@astrojs/react": ^6.0.2
  "@astrojs/rss": ^4.0.19
  "@astrojs/starlight": ^0.41.7
  "@astrojs/vercel": ^11.0.5
  astro: ^7.2.0
  mdast-util-find-and-replace: ^3.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
