packages:
  - apps/*
  - packages/*

patchedDependencies:
  "@effect/doctest@4.0.0-beta.104": patches/@effect__doctest@4.0.0-beta.104.patch
  astro-tweet@0.0.6: patches/astro-tweet.patch

supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current

allowBuilds:
  "@mixedbread/cli": true
  esbuild: false
  msgpackr-extract: false
  msw: false
  sharp: false

minimumReleaseAgeExclude:
  - "@effect/atom-react@4.0.0-beta.104"
  - "@effect/platform-browser@4.0.0-beta.104"
  - "@effect/platform-node-shared@4.0.0-beta.104"
  - "@effect/platform-node@4.0.0-beta.104"
  - effect@4.0.0-beta.104
  - "@effect/doctest@4.0.0-beta.104"
catalogMode: prefer

catalog:
  mdast-util-find-and-replace: ^3.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
