packages:
  - scripts/api-reference

patchedDependencies:
  astro-tweet@0.0.6: patches/astro-tweet.patch

supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current

allowBuilds:
  "@mixedbread/cli": true
  esbuild: false
  msgpackr-extract: false
  msw: false
  sharp: false
