name: Sync Mixedbread Vector Store

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [content/src/content/docs/**/*.mdx]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/setup
        with:
          working-directory: ./content

      - name: Sync vector store
        shell: bash
        working-directory: ./content
        env:
          MXBAI_API_KEY: ${{ secrets.MXBAI_API_KEY }}
          MXBAI_VECTOR_STORE_ID: ${{ secrets.MXBAI_VECTOR_STORE_ID }}
        run: |
          find "src/content/docs/docs" -type f -name "*.mdx" | while read -r file; do
            # Extract the URL path for the file
            urlPath="${file#src/content/docs}"
            urlPath="${urlPath%.mdx}"

            # Sync the file to the vector store with the relevant metadata
            pnpm mxbai vs sync "${MXBAI_VECTOR_STORE_ID}" "${file}" \
              --yes \
              --strategy fast \
              --metadata "{ \"urlPath\": \"${urlPath}\" }" \
              --dry-run 
          done 

